"use client"

import React from "react";
import FlashSale from "@/components/FlashSale";

// Mock flash sale data
const flashSaleProducts = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    originalPrice: 129999,
    salePrice: 99999,
    discount: 23,
    image: "/placeholder.svg",
    soldCount: 45,
    totalStock: 100,
    category: "Electronics",
    brand: "Apple",
    rating: 4.8,
    reviews: 1250,
    isNew: true,
    isTrending: true,
  },
  {
    id: "2",
    name: "Samsung 65-inch 4K Smart TV",
    originalPrice: 89999,
    salePrice: 59999,
    discount: 33,
    image: "/placeholder.svg",
    soldCount: 78,
    totalStock: 150,
    category: "Electronics",
    brand: "Samsung",
    rating: 4.6,
    reviews: 890,
    isTrending: true,
  },
  {
    id: "3",
    name: "MacBook Air M2",
    originalPrice: 114999,
    salePrice: 89999,
    discount: 22,
    image: "/placeholder.svg",
    soldCount: 32,
    totalStock: 80,
    category: "Electronics",
    brand: "Apple",
    rating: 4.9,
    reviews: 567,
    isNew: true,
  },
  {
    id: "4",
    name: "Sony WH-1000XM5 Headphones",
    originalPrice: 29999,
    salePrice: 19999,
    discount: 33,
    image: "/placeholder.svg",
    soldCount: 156,
    totalStock: 200,
    category: "Electronics",
    brand: "Sony",
    rating: 4.7,
    reviews: 2340,
    isTrending: true,
  },
  {
    id: "5",
    name: "Nike Air Max 270",
    originalPrice: 12999,
    salePrice: 7999,
    discount: 38,
    image: "/placeholder.svg",
    soldCount: 89,
    totalStock: 120,
    category: "Fashion",
    brand: "Nike",
    rating: 4.5,
    reviews: 678,
  },
  {
    id: "6",
    name: "Adidas Ultraboost 22",
    originalPrice: 15999,
    salePrice: 9999,
    discount: 38,
    image: "/placeholder.svg",
    soldCount: 67,
    totalStock: 100,
    category: "Fashion",
    brand: "Adidas",
    rating: 4.6,
    reviews: 445,
  },
  {
    id: "7",
    name: "Canon EOS R6 Mark II",
    originalPrice: 249999,
    salePrice: 189999,
    discount: 24,
    image: "/placeholder.svg",
    soldCount: 12,
    totalStock: 50,
    category: "Electronics",
    brand: "Canon",
    rating: 4.8,
    reviews: 234,
    isNew: true,
  },
  {
    id: "8",
    name: "Dell XPS 13 Laptop",
    originalPrice: 99999,
    salePrice: 74999,
    discount: 25,
    image: "/placeholder.svg",
    soldCount: 34,
    totalStock: 75,
    category: "Electronics",
    brand: "Dell",
    rating: 4.4,
    reviews: 189,
  },
  {
    id: "9",
    name: "Bose QuietComfort 45",
    originalPrice: 24999,
    salePrice: 16999,
    discount: 32,
    image: "/placeholder.svg",
    soldCount: 123,
    totalStock: 180,
    category: "Electronics",
    brand: "Bose",
    rating: 4.6,
    reviews: 892,
    isTrending: true,
  },
  {
    id: "10",
    name: "LG 55-inch OLED TV",
    originalPrice: 129999,
    salePrice: 89999,
    discount: 31,
    image: "/placeholder.svg",
    soldCount: 56,
    totalStock: 90,
    category: "Electronics",
    brand: "LG",
    rating: 4.7,
    reviews: 456,
  },
  {
    id: "11",
    name: "Puma RS-X Sneakers",
    originalPrice: 8999,
    salePrice: 5499,
    discount: 39,
    image: "/placeholder.svg",
    soldCount: 234,
    totalStock: 300,
    category: "Fashion",
    brand: "Puma",
    rating: 4.3,
    reviews: 567,
  },
  {
    id: "12",
    name: "Under Armour HOVR",
    originalPrice: 10999,
    salePrice: 6999,
    discount: 36,
    image: "/placeholder.svg",
    soldCount: 89,
    totalStock: 150,
    category: "Fashion",
    brand: "Under Armour",
    rating: 4.4,
    reviews: 234,
  },
];

export default function FlashSalePage() {
  // Set flash sale end time (24 hours from now)
  const endTime = new Date();
  endTime.setHours(endTime.getHours() + 24);

  return (
    <div className="min-h-screen bg-gradient-to-br from-red-50 via-orange-50 to-yellow-50">
      <FlashSale
        title="MEGA FLASH SALE - 24 HOURS ONLY!"
        endTime={endTime}
        products={flashSaleProducts}
      />
    </div>
  );
} 